triggers:
  on_commit: true    # Run lint checks after commits
  on_push: true      # Run security checks before push
  on_save: false     # Run quick checks on file save (IDE integration)
  ci_integration: true  # Include in dev-workflow auto-correction

checks:
  default: [lint, security, performance]
  on_commit: [lint]  # Lightweight for frequent triggers
  on_push: [security]  # Security-focused for pushes
  on_save: [lint]    # Quick feedback

exclusions:
  files:
    - "*.min.js"
    - "node_modules/**"
    - "__pycache__/**"
    - ".git/**"
  directories:
    - "build/"
    - "dist/"

languages:
  python:
    tools: [pylint, flake8, bandit]
  javascript:
    tools: [eslint]
  # Add more as needed

severity_thresholds:
  fail_on: [error, high]  # Exit with error for these severities
  warn_on: [warning, medium]

auto_fix: false  # Experimental: attempt automatic fixes